title: Diego250xYT
description: Backend developer crafting tools, proxies, and automation.
url: "https://diego250xyt.github.io"
baseurl: ""
markdown: kramdown
permalink: /blog/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
